const sample_tokens: EvmToken[] = [
  {
    name: "Ethereum",
    symbol: "ETH",
    logo: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    contractAddress: "0x0000000000000000000000000000000000000000",
    usdPrice: 1800,
    chainId: 1,
    decimals: 18,
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    logo: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png",
    contractAddress: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    usdPrice: 1,
    chainId: 1,
    decimals: 6,
  },
  {
    name: "Tether",
    symbol: "USDT",
    logo: "https://cryptologos.cc/logos/tether-usdt-logo.png",
    contractAddress: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    usdPrice: 1,
    chainId: 1,
    decimals: 6,
  },
  {
    name: "Binance Coin",
    symbol: "BNB",
    logo: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
    contractAddress: "0xb8c77482e45f1f44de1745f52c74426c631bdd52",
    usdPrice: 230,
    chainId: 56,
    decimals: 18,
  },
  {
    name: "Cardano",
    symbol: "ADA",
    logo: "https://cryptologos.cc/logos/cardano-ada-logo.png",
    contractAddress: "N/A",
    usdPrice: 0.28,
    chainId: 1,
    decimals: 6,
  },
  {
    name: "Solana",
    symbol: "SOL",
    logo: "https://cryptologos.cc/logos/solana-sol-logo.png",
    contractAddress: "N/A",
    usdPrice: 25,
    chainId: 1,
    decimals: 9,
  },
  {
    name: "Polygon",
    symbol: "MATIC",
    logo: "https://cryptologos.cc/logos/polygon-matic-logo.png",
    contractAddress: "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0",
    usdPrice: 1.2,
    chainId: 137,
    decimals: 18,
  },
  {
    name: "Polkadot",
    symbol: "DOT",
    logo: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
    contractAddress: "N/A",
    usdPrice: 4.6,
    chainId: 1,
    decimals: 10,
  },
  {
    name: "Chainlink",
    symbol: "LINK",
    logo: "https://cryptologos.cc/logos/chainlink-link-logo.png",
    contractAddress: "0x514910771af9ca656af840dff83e8264ecf986ca",
    usdPrice: 8,
    chainId: 1,
    decimals: 18,
  },
  {
    name: "Avalanche",
    symbol: "AVAX",
    logo: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
    contractAddress: "N/A",
    usdPrice: 14,
    chainId: 43114,
    decimals: 18,
  },
  {
    name: "Shiba Inu",
    symbol: "SHIB",
    logo: "https://cryptologos.cc/logos/shiba-inu-shib-logo.png",
    contractAddress: "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE",
    usdPrice: 0.00001,
    chainId: 1,
    decimals: 18,
  },
  {
    name: "Uniswap",
    symbol: "UNI",
    logo: "https://cryptologos.cc/logos/uniswap-uni-logo.png",
    contractAddress: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    usdPrice: 4,
    chainId: 1,
    decimals: 18,
  },
  {
    name: "Wrapped Bitcoin",
    symbol: "WBTC",
    logo: "https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.png",
    contractAddress: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    usdPrice: 36000,
    chainId: 1,
    decimals: 8,
  },
  {
    name: "Dai",
    symbol: "DAI",
    logo: "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png",
    contractAddress: "0x6b175474e89094c44da98b954eedeac495271d0f",
    usdPrice: 1,
    chainId: 1,
    decimals: 18,
  },
  {
    name: "Litecoin",
    symbol: "LTC",
    logo: "https://cryptologos.cc/logos/litecoin-ltc-logo.png",
    contractAddress: "N/A",
    usdPrice: 65,
    chainId: 1,
    decimals: 8,
  },
  {
    name: "Cosmos",
    symbol: "ATOM",
    logo: "https://cryptologos.cc/logos/cosmos-atom-logo.png",
    contractAddress: "N/A",
    usdPrice: 10,
    chainId: 1,
    decimals: 6,
  },
  {
    name: "Bitcoin Cash",
    symbol: "BCH",
    logo: "https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png",
    contractAddress: "N/A",
    usdPrice: 240,
    chainId: 1,
    decimals: 8,
  },
  {
    name: "Stellar",
    symbol: "XLM",
    logo: "https://cryptologos.cc/logos/stellar-xlm-logo.png",
    contractAddress: "N/A",
    usdPrice: 0.1,
    chainId: 1,
    decimals: 6,
  },
  {
    name: "VeChain",
    symbol: "VET",
    logo: "https://cryptologos.cc/logos/vechain-vet-logo.png",
    contractAddress: "0xd850942ef8811f2a866692a623011bde52a462c1",
    usdPrice: 0.02,
    chainId: 1,
    decimals: 18,
  },
  {
    name: "Theta",
    symbol: "THETA",
    logo: "https://cryptologos.cc/logos/theta-theta-logo.png",
    contractAddress: "N/A",
    usdPrice: 0.65,
    chainId: 1,
    decimals: 18,
  },
];
