import type { Metadata } from "next";
import "../style/globals.css";
import HeaderPage from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="dark relative w-full max-w-[1920px] bg-background-dark flex flex-col mx-auto">
        <HeaderPage />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
