import type { Metadata } from "next";
import "../style/globals.css";
import HeaderPage from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      {/* TEMP: Temporary code for testing purposes (h-screen) */}
      <body className="relative w-full max-w-[1920px] bg-background-dark">
        <HeaderPage />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
