import type { Metadata } from "next";
import "../style/globals.css";
import HeaderPage from "@/components/layout/header";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html
      lang="en"
      className="dark bg-[#060607] bg-no-repeat h-screen">
      <body
        className={cn(
          "relative max-w-[1920px] mx-auto w-full h-full",
          "flex flex-col items-center justify-between"
        )}>
        <HeaderPage />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;