const chains: Chain[] = [
  {
    chainId: 0,
    name: "Internet Computer",
    nativeTokenSymbol: "ICP",
    scannerAddress: "https://dashboard.internetcomupter.org",
    depositHelperAddress: null,
    type: "ICP",
    disabled: false,
    logo: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
  },
  {
    chainId: 1,
    name: "Ethereum",
    nativeTokenSymbol: "ETH",
    scannerAddress: "https://etherscan.io",
    depositHelperAddress: "0xDepositHelperAddressExample1",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
  },
  {
    chainId: 42161,
    name: "Arbitrum One",
    nativeTokenSymbol: "ETH",
    scannerAddress: "https://arbiscan.io",
    depositHelperAddress: "0xDepositHelperAddressExample3",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.png",
  },
  {
    chainId: 56,
    name: "Binance Smart Chain (BSC)",
    nativeTokenSymbol: "BNB",
    scannerAddress: "https://bscscan.com",
    depositHelperAddress: "0xDepositHelperAddressExample4",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
  },
  {
    chainId: 97,
    name: "Binance Smart Chain Testnet (BSC Testnet)",
    nativeTokenSymbol: "BNB",
    scannerAddress: "https://testnet.bscscan.com",
    depositHelperAddress: "0xDepositHelperAddressExample5",
    type: "EVM",
    disabled: false,
    logo: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
  },
  {
    chainId: 137,
    name: "Polygon",
    nativeTokenSymbol: "MATIC",
    scannerAddress: "https://polygonscan.com",
    depositHelperAddress: "0xDepositHelperAddressExample6",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/polygon-matic-logo.png",
  },
  {
    chainId: 10,
    name: "Optimism",
    nativeTokenSymbol: "ETH",
    scannerAddress: "https://optimistic.etherscan.io",
    depositHelperAddress: "0xDepositHelperAddressExample7",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/optimism-op-logo.png",
  },
  {
    chainId: 8453,
    name: "Base",
    nativeTokenSymbol: "ETH",
    scannerAddress: "https://basescan.org",
    depositHelperAddress: "0xDepositHelperAddressExample8",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/base-logo.png",
  },
  {
    chainId: 43114,
    name: "Avalanche",
    nativeTokenSymbol: "AVAX",
    scannerAddress: "https://snowtrace.io",
    depositHelperAddress: "0xDepositHelperAddressExample9",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
  },
  {
    chainId: 250,
    name: "Fantom",
    nativeTokenSymbol: "FTM",
    scannerAddress: "https://ftmscan.com",
    depositHelperAddress: "0xDepositHelperAddressExample10",
    type: "EVM",
    disabled: true,
    logo: "https://cryptologos.cc/logos/fantom-ftm-logo.png",
  },
];
